(function(W){
 const old=W.assets.draw,masters=['castle','city','bridge','temple'].map(()=>new Image()),cache=new Map(),levels=W.config.render.assets.lodSizes,budget=W.config.render.assets.cacheBytes;let bytes=0;const prepared=new Map();
 const aliases={56:0,54:1,80:2,64:3};
 const loaded=Promise.all(masters.map((image,i)=>new Promise(resolve=>{image.onload=()=>resolve(true);image.onerror=()=>resolve(false);const name=['castle','city','bridge','temple'][i];image.src=W['master'+name+'Data']||'assets/master-'+name+'.png';})));W.assets.ready=Promise.all([W.assets.ready,loaded]);
 function sample(source,key,pixels){const native=source.sw,target=levels.find(n=>n>=pixels)||native;if(target>=native)return source;const id=key+':'+target;if(cache.has(id)){const s=cache.get(id);cache.delete(id);cache.set(id,s);return s;}const canvas=document.createElement('canvas');canvas.width=target;canvas.height=Math.max(1,Math.round(target*source.sh/source.sw));const c=canvas.getContext('2d');c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(source.image,source.sx,source.sy,source.sw,source.sh,0,0,canvas.width,canvas.height);const s={image:canvas,sx:0,sy:0,sw:canvas.width,sh:canvas.height,bytes:canvas.width*canvas.height*4};cache.set(id,s);bytes+=s.bytes;while(bytes>budget&&cache.size>1){const first=cache.keys().next().value;bytes-=cache.get(first).bytes;cache.delete(first);}return s;}
 function source(id){const m=id>=104?id-104:aliases[id];if(m!==undefined&&masters[m]?.naturalWidth)return{image:masters[m],sx:0,sy:0,sw:masters[m].naturalWidth,sh:masters[m].naturalHeight};return W.assets.source(id);}
 W.assets.draw=function(c,id,x,y,width,variant=0,opacity=1){const src=source(id);if(!src?.image.complete||!src.sw)return false;if(!prepared.has(id))prepared.set(id,W.atlas?.soften(src,id)||src);const tr=c.getTransform(),pixels=width*Math.hypot(tr.a,tr.b),s=sample(prepared.get(id),'sprite-'+id,pixels);c.save();c.globalAlpha*=opacity;c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.translate(x,y);if(variant>.65)c.scale(-1,1);c.drawImage(s.image,s.sx,s.sy,s.sw,s.sh,-width/2,-width*.8,width,width);c.restore();W.assets.lastLOD={id,requestedPixels:pixels,sourcePixels:src.sw,sampledPixels:s.sw};return true;};
 W.assets.drawRaster=function(c,image,key,x,y,width,anchor,rotation=0){if(!image?.naturalWidth)return false;const tr=c.getTransform(),s=sample({image,sx:0,sy:0,sw:image.naturalWidth,sh:image.naturalHeight},key,width*Math.hypot(tr.a,tr.b)),h=width*image.naturalHeight/image.naturalWidth;c.save();c.imageSmoothingQuality='high';c.translate(x,y);c.rotate(rotation*Math.PI/180);c.drawImage(s.image,s.sx,s.sy,s.sw,s.sh,-width*anchor.x,-h*anchor.y,width,h);c.restore();return true;};
 W.assets.masterSource=source;W.assets.nativeResolution=id=>Number.isInteger(id)?source(id)?.sw||0:0;W.assets.lodStats=()=>({bytes,entries:cache.size,budget,preparedBytes:[...prepared.values()].reduce((n,s)=>n+(s.removedBleed!==undefined?s.sw*s.sh*4:0),0)});
})(WS);
