(function(W){
 const curves=new WeakMap(),S=W.semantic;
 // Two corner-cutting passes soften grid turns; source points and endpoints stay authoritative.
 function curve(item){const signature=item.points.reduce((a,p,i)=>a+(p.x*31+p.y)*(i+1),item.points.length),cached=curves.get(item);if(cached?.source===item.points&&cached.signature===signature)return cached.points;let pts=item.points.map(p=>({...p}));for(let pass=0;pass<2&&pts.length>2;pass++){const next=[pts[0]];for(let i=0;i<pts.length-1;i++){const a=pts[i],b=pts[i+1];next.push({x:a.x*.75+b.x*.25,y:a.y*.75+b.y*.25},{x:a.x*.25+b.x*.75,y:a.y*.25+b.y*.75});}next.push(pts.at(-1));pts=next;}curves.set(item,{source:item.points,signature,points:pts});return pts;}
 function ground(c,p,r){if(!p.styling.texture)return;const step=28,amount=p.styling.texture/100;c.save();for(let gy=Math.floor((r.y-35)/step);gy*step<r.y+r.height+35;gy++)for(let gx=Math.floor((r.x-35)/step);gx*step<r.x+r.width+35;gx++){const v=S.random(p,'atlas-ground',gx,gy),x=(gx+v)*step,y=(gy+S.random(p,'atlas-ground-y',gx,gy))*step;if(x<0||y<0||x>=p.width||y>=p.height)continue;const i=W.model.index(p,x,y),b=p.biomes[i];if(p.terrain[i]<p.seaLevel+.025||v<.25)continue;const wet=b==='swamp',rock=['mountain','rocky','snow'].includes(b),forest=W.config.biomes[b]?.layer==='Vegetation';c.save();c.translate(x,y);c.rotate(v*.7-.35);c.globalAlpha=amount*(wet?.18:.085);c.fillStyle=wet?'#244d46':rock?'#515744':forest?'#283f29':v>.65?'#c3b270':'#53673c';c.beginPath();c.moveTo(-13,0);c.bezierCurveTo(-18,-5,-5,-8,5,-5);c.bezierCurveTo(21,-8,23,3,10,4);c.bezierCurveTo(3,8,-7,3,-13,0);c.fill();if(!wet&&!rock&&!forest){c.globalAlpha=amount*.25;c.strokeStyle=v>.65?'#c1bb82':'#475d32';c.lineWidth=.45;c.beginPath();for(let k=0;k<7;k++){const gx=S.random(p,'grass-patch-x',Math.floor(x),Math.floor(y),k)*19-9,gy=S.random(p,'grass-patch-y',Math.floor(x),Math.floor(y),k)*8-4;c.moveTo(gx-1,gy+1);c.quadraticCurveTo(gx+1,gy-1,gx,gy-3);c.moveTo(gx,gy+1);c.lineTo(gx+2,gy-1);}c.stroke();}if(wet){c.strokeStyle='#bdc19a';c.lineWidth=.4;c.beginPath();c.moveTo(-10,1);c.quadraticCurveTo(0,4,12,0);c.stroke();}c.restore();}c.restore();}
 function footing(c,p,o){const d=W.config.objects[o.type];if(!d||d.custom||o.layer==='Decorations'||['bridge','royalbridge','stonebridge','longbridge','waterfall','ford'].includes(o.type))return;const {x,y}=o.position,i=W.model.index(p,x,y);if(p.terrain[i]<p.seaLevel+.02)return;const size=Math.min(75,d.size*(o.scale||1));c.save();c.translate(x,y);c.scale(1,.32);const g=c.createRadialGradient(0,0,0,0,0,size*.5);g.addColorStop(0,'#514b2a48');g.addColorStop(.55,'#81744925');g.addColorStop(1,'#81744900');c.fillStyle=g;c.fillRect(-size*.5,-size*.5,size,size);c.restore();}
 function shadow(c,s){c.save();c.globalAlpha=.13;c.fillStyle='#15291c';c.beginPath();c.ellipse(s.x+s.size*.035,s.y-s.size*.045,s.size*.36,s.size*.065,0,0,Math.PI*2);c.fill();c.restore();}
 // Atlas drawings can cross cell borders. Remove only detached, shallow components
 // touching the upper crop edge; retain the principal silhouette and separate trees.
 function removeBleed(data,width,height){const seen=new Uint8Array(width*height);let removed=0;for(let start=0;start<width*3;start++){if(seen[start]||data[start*4+3]<6)continue;const queue=[start];seen[start]=1;let bottom=0;for(let k=0;k<queue.length;k++){const i=queue[k],x=i%width,y=Math.floor(i/width);bottom=Math.max(bottom,y);for(const j of [x?i-1:-1,x<width-1?i+1:-1,y?i-width:-1,y<height-1?i+width:-1])if(j>=0&&!seen[j]&&data[j*4+3]>=6){seen[j]=1;queue.push(j);}}if(bottom>=height*.18||queue.length>width*height*.1)continue;for(const i of queue){data[i*4+3]=0;removed++;}}return removed;}
 // Source-sized alpha preparation, not a higher-resolution replacement image.
 function soften(source,id){if(!([0,1,2,4,5,6,7].includes(id)||id>=16&&id<=31))return source;const canvas=new OffscreenCanvas(Math.floor(source.sw),Math.floor(source.sh)),c=canvas.getContext('2d');c.drawImage(source.image,source.sx,source.sy,source.sw,source.sh,0,0,canvas.width,canvas.height);let removedBleed=0;if(id>=16&&id<=31){const pixels=c.getImageData(0,0,canvas.width,canvas.height);removedBleed=removeBleed(pixels.data,canvas.width,canvas.height);c.putImageData(pixels,0,0);}c.globalCompositeOperation='destination-in';const g=c.createLinearGradient(0,0,0,canvas.height);g.addColorStop(0,'#000');g.addColorStop(id<=2||id>=16&&id<=23?.78:.9,'#000');g.addColorStop(1,'#0000');c.fillStyle=g;c.fillRect(0,0,canvas.width,canvas.height);return{...source,image:canvas,sx:0,sy:0,sw:canvas.width,sh:canvas.height,removedBleed};}
 W.atlas={curve,ground,footing,shadow,soften,removeBleed};
})(WS);
