(function(W){
 const categories={settlements:'Поселения',military:'Укрепления',sacred:'Святыни и магия',ruins:'Руины и древности',nature:'Природа',infrastructure:'Инфраструктура',fantasy:'Легендарные места'};
 const groups={
 settlements:[['smallhouse','Маленький дом',40,28],['house','Дом',41,36],['longhouse','Длинный дом',42,46],['farm','Ферма',43,58],['hamlet','Хутор',44,48],['village','Деревня',45,62],['largevillage','Большая деревня',46,78],['town','Городок',47,85],['city','Город',48,100],['largecity','Большой город',49,125],['capital','Столица',50,145],['fishingvillage','Рыбацкая деревня',51,65],['mountainsettlement','Горное поселение',52,70],['forestsettlement','Лесное поселение',53,70],['portcity','Портовый город',54,110],['tradecity','Торговый город',55,105]],
 military:[['castle','Замок',56,95],['fortress','Крепость',57,100],['citadel','Цитадель',58,115],['bastion','Бастион',59,78],['outpost','Форпост',60,62],['watchtower','Сторожевая башня',61,50],['tower','Дозорная башня',11,50],['gate','Ворота',62,45],['citygate','Городские врата',62,70],['fortifiedgate','Укреплённые врата',62,90],['wall','Стена',63,80],['wallsection','Участок стены',63,45]],
 sacred:[['temple','Храм',64,75],['chapel','Часовня',65,48],['shrine','Святилище',35,40],['altar','Алтарь',67,42],['monastery','Монастырь',66,85],['sacredtree','Священное дерево',14,80],['monument','Круг камней',13,60],['magicarch','Магическая арка',70,65],['portal','Портал',71,60],['obelisk','Обелиск',69,55],['statue','Статуя',68,45],['giantstatue','Гигантская статуя',68,95],['runemonument','Рунический монумент',69,72]],
 ruins:[['house_ruin','Руины дома',72,42],['tower_ruin','Руины башни',73,52],['ruins','Руины крепости',74,85],['abandonedtemple','Заброшенный храм',75,70],['crypt','Древний склеп',76,48],['brokenarch','Разрушенная арка',77,50],['columns','Древние колонны',78,65],['collapsedwall','Обвалившиеся стены',39,55],['ancientbridge','Древний мост',79,70],['lostruins','Затерянные руины',9,80]],
 nature:[['bigmountain','Большая гора',0,135],['smallmountain','Малая гора',16,65],['snowmountain','Снежная гора',20,100],['rockypeak','Скалистый пик',18,85],['rockmass','Скальный массив',2,90],['rock','Одиночная скала',88,27],['cliff','Утёс',89,85],['waterfall','Водопад',36,45],['bigwaterfall','Большой водопад',97,100],['canyon','Каньон',90,115],['cave','Пещера',91,55],['caveentrance','Вход в пещеру',91,32],['ancientoak','Древний дуб',92,105],['deadtree','Мёртвое дерево',93,55],['forestcluster','Лесной кластер',24,75],['marsh','Болото',94,70],['islet','Островок',95,90],['reefs','Рифы',96,75]],
 infrastructure:[['bridge','Мост',80,40],['stonebridge','Каменный мост',80,65],['woodbridge','Деревянный мост',81,60],['longbridge','Длинный мост',80,100],['roadpiece','Дорога',null,55],['crossroads','Перекрёсток',null,65],['harbor','Гавань',82,100],['port','Порт',82,80],['dock','Док',82,50],['lighthouse','Маяк',83,65],['pier','Пристань',82,35],['market','Рынок',99,65],['caravancamp','Караванный лагерь',98,68]],
 fantasy:[['magetower','Башня мага',84,80],['blackcitadel','Чёрная цитадель',58,135],['dragonbones','Драконьи кости',85,100],['abyssportal','Портал бездны',100,90],['cursedaltar','Проклятый алтарь',101,65],['ruinedthrone','Трон в руинах',86,70],['moonmonolith','Лунный монолит',102,70],['astralgate','Астральные врата',70,100],['necromancertower','Башня некроманта',84,95],['forgottenlibrary','Забытая библиотека',87,95],['worldtree','Древо мира',14,130],['holyspring','Святой источник',103,65]]};
 const affinity={settlements:['plain','valley','coast'],military:['rocky','plain','mountain'],sacred:['forest','valley','plain'],ruins:['ruined','waste','deadforest'],nature:['rocky','mountain','forest'],infrastructure:['coast','valley','plain'],fantasy:['cursed','forest','snow']};
 for(const [category,rows]of Object.entries(groups))for(const [id,name,sprite,size]of rows){const old=W.config.objects[id]||{};W.config.objects[id]={...old,id,name,category,description:categories[category]+' · '+name+'. Рисованный ориентир для вашего атласа.',icon:old.icon||'◇',layer:old.layer||(['settlements','military','ruins','infrastructure'].includes(category)?'Structures':category==='nature'?'Decorations':'POI'),sprite:sprite===null?undefined:sprite,size,recommendedSize:{width:size>90?512:256,height:size>90?512:256},scaleRange:[.25,3],anchor:{x:.5,y:.8},tags:[category,name.toLowerCase()],rarity:category==='fantasy'?.18:.65,biomeAffinity:affinity[category],placementRules:{minElevation:0,maxElevation:category==='settlements'?.72:1,minSpacing:size*.95,coastal:['portcity','fishingvillage','harbor','port','dock','lighthouse','pier'].includes(id),remote:['ruins','fantasy'].includes(category),nearRiver:['bridge','stonebridge','woodbridge','longbridge','waterfall','bigwaterfall'].includes(id)},assetKind:'atlas2d',assetPath:sprite==null?'procedural':sprite>=88?'assets/wilds-v3.png':sprite>=72?'assets/relics-v3.png':sprite>=56?'assets/citadels-v3.png':sprite>=40?'assets/settlements-v3.png':sprite>=32?'assets/landmarks.png':sprite>=16?'assets/details.png':'assets/atlas.png'};W.config.objects[id].previewPath=W.config.objects[id].assetPath;}
 for(const [id,d]of Object.entries(W.config.objects))Object.assign(d,{id,category:d.category||'nature',description:d.description||d.name,assetKind:d.assetKind||'atlas2d',assetPath:d.assetPath||'assets/atlas.png',previewPath:d.previewPath||'assets/atlas.png',recommendedSize:d.recommendedSize||{width:256,height:256},scaleRange:d.scaleRange||[.25,3],anchor:d.anchor||{x:.5,y:.8},tags:d.tags||[],placementRules:d.placementRules||{},rarity:d.rarity??.5,biomeAffinity:d.biomeAffinity||[]});
 for(const id of ['portcity','fishingvillage','harbor','port','dock','lighthouse','pier'])W.config.objects[id].biomeAffinity=['coast','plain','valley','rocky'];
 W.config.objects.mountainsettlement.biomeAffinity=['rocky','mountain'];W.config.objects.mountainsettlement.placementRules.maxElevation=.84;
 W.config.objects.forestsettlement.biomeAffinity=['forest','conifer'];
 for(const id of ['abyssportal','cursedaltar','blackcitadel','necromancertower'])W.config.objects[id].biomeAffinity=['cursed','deadforest','ruined'];
 for(const [id,category]of Object.entries({camp:'infrastructure',dungeon:'ruins',cemetery:'ruins',fire:'infrastructure',ford:'infrastructure'}))W.config.objects[id].category=category;
 for(const d of Object.values(W.config.objects))if(d.sprite===undefined){d.assetKind='procedural2d';d.assetPath='procedural:'+d.id;d.previewPath=d.assetPath;}
 for(const [id,name,sprite,base,size,file]of [['royalcastle','Королевский замок',104,'castle',145,'castle'],['maritimecapital','Морская столица',105,'portcity',180,'city'],['royalbridge','Королевский мост',106,'stonebridge',110,'bridge'],['grandcathedral','Великий собор',107,'temple',125,'temple']])W.config.objects[id]={...W.config.objects[base],id,name,sprite,size,description:name+' · детальный мастер для глубокого приближения.',assetPath:'assets/master-'+file+'.png',previewPath:'assets/master-'+file+'.png',recommendedSize:{width:1024,height:1024},tags:[...W.config.objects[base].tags,'master','high-resolution']};
 for(const [id,file]of [['castle','castle'],['portcity','city'],['bridge','bridge'],['stonebridge','bridge'],['longbridge','bridge'],['temple','temple']])Object.assign(W.config.objects[id],{assetPath:'assets/master-'+file+'.png',previewPath:'assets/master-'+file+'.png',recommendedSize:{width:1024,height:1024}});
 W.config.categories=categories;
 W.catalog={groups,categories,search(query='',category='',mine=false){const q=query.toLocaleLowerCase().trim();return Object.values(W.config.objects).filter(d=>(!mine||d.custom)&&(!category||d.category===category)&&(!q||[d.name,d.description,...d.tags].join(' ').toLocaleLowerCase().includes(q)));}};
})(WS);
