window.WS = window.WS || {};
(function(W) {
 const base={landMass:67,humidity:60,temperature:55,mountains:58,forests:65,swamp:24,rivers:65,islands:28,ruins:48,settlements:48,roads:72,fantasy:45,corruption:12};
 const preset=(description,settings,colors)=>({description,params:{...base,...settings},colors});
 W.config={version:2,cellSize:5,maxSize:3200,sizes:{Small:[1000,700],Medium:[1800,1200],Large:[2800,1900]},
 layers:['Terrain','Height','Water','Rivers','Mountains','Vegetation','Roads','Structures','POI','Decorations','Labels'],
 parameters:{landMass:'Площадь суши',humidity:'Влажность',temperature:'Температура',mountains:'Высота гор',forests:'Плотность леса',swamp:'Болотистость',rivers:'Речная сеть',islands:'Частота островов',ruins:'Древние руины',settlements:'Поселения',roads:'Дороги',fantasy:'Магия мира',corruption:'Скверна'},
 generation:{seaLevel:.46,edgeFalloff:5,noiseOctaves:5,riverMinLength:9,lakeDepth:.032,settlementSpacing:115,decorativeSpacing:25},
 biomes:{
 plain:{name:'Луга и равнины',color:'#8c8d60',layer:'Terrain'},forest:{name:'Древняя чаща',color:'#4f6241',layer:'Vegetation',sprite:4},conifer:{name:'Хвойный лес',color:'#465a48',layer:'Vegetation',sprite:5},swamp:{name:'Болотные земли',color:'#647b65',layer:'Vegetation',sprite:7},rocky:{name:'Каменистые земли',color:'#8a8770',layer:'Mountains',sprite:2},mountain:{name:'Высокие горы',color:'#92917e',layer:'Mountains',sprite:0},snow:{name:'Снежные вершины',color:'#c5cdbe',layer:'Mountains',sprite:1},waste:{name:'Пустоши',color:'#aaa07c',layer:'Terrain'},ruined:{name:'Погибшая империя',color:'#827a61',layer:'Terrain'},deadforest:{name:'Мёртвый лес',color:'#65694e',layer:'Vegetation',sprite:6},valley:{name:'Речная долина',color:'#879967',layer:'Terrain'},coast:{name:'Побережье',color:'#b8ad83',layer:'Terrain'},tundra:{name:'Тундра',color:'#9aa18a',layer:'Terrain'},cursed:{name:'Проклятые земли',color:'#69645b',layer:'Vegetation',sprite:6}},
 objects:{
 castle:{name:'Замок',icon:'♜',layer:'Structures',sprite:8,size:88},fortress:{name:'Крепость',icon:'♜',layer:'Structures',sprite:33,size:95},city:{name:'Город',icon:'▥',layer:'Structures',sprite:10,size:85},village:{name:'Деревня',icon:'⌂',layer:'Structures',sprite:10,size:53},camp:{name:'Лагерь',icon:'△',layer:'POI',sprite:32,size:44},tower:{name:'Башня',icon:'♖',layer:'Structures',sprite:11,size:48},ruins:{name:'Руины',icon:'♜',layer:'Structures',sprite:39,size:65},temple:{name:'Храм',icon:'♧',layer:'Structures',sprite:12,size:65},portal:{name:'Портал',icon:'◉',layer:'POI',sprite:15,size:49},cave:{name:'Пещера',icon:'◒',layer:'POI',size:27},bridge:{name:'Мост',icon:'╫',layer:'Structures',size:26},ford:{name:'Брод',icon:'≈',layer:'Decorations',size:19},monument:{name:'Древний круг',icon:'◇',layer:'POI',sprite:13,size:60},dungeon:{name:'Вход в подземелье',icon:'◒',layer:'POI',sprite:9,size:35},worldtree:{name:'Мировое древо',icon:'♠',layer:'POI',sprite:14,size:105},shrine:{name:'Святилище',icon:'✧',layer:'POI',sprite:35,size:35},watchtower:{name:'Сторожевая башня',icon:'♖',layer:'Structures',sprite:38,size:46},tree:{name:'Дерево',icon:'♠',layer:'Decorations',sprite:4,size:35},rock:{name:'Валуны',icon:'◆',layer:'Decorations',sprite:2,size:21},waterfall:{name:'Водопад',icon:'≋',layer:'Decorations',sprite:36,size:39},cemetery:{name:'Кладбище',icon:'✝',layer:'Decorations',sprite:34,size:33},fire:{name:'Костёр',icon:'✦',layer:'Decorations',size:12}},
 presets:{
 'Classic Fantasy':preset('Зелёные королевства, серебряные реки и легенды за каждым перевалом.',{},['#96a16c','#4b674e','#64858a']),
 'Dark Fantasy':preset('Тёмные цитадели над мрачными лесами. Древняя магия ещё дышит в руинах.',{humidity:69,temperature:43,mountains:64,forests:72,swamp:42,ruins:76,corruption:53,fantasy:70,settlements:35},['#667454','#303e39','#57777c']),
 'Northern Kingdom':preset('Ледяные реки, хвойные леса и белые хребты на краю обитаемого мира.',{temperature:14,mountains:80,forests:58,islands:42,swamp:8,corruption:4},['#cad3c8','#536960','#698e9e']),
 'Swamp Lands':preset('Туманные низины, затопленные храмы и тропы среди древних ив.',{landMass:54,humidity:94,temperature:66,mountains:19,swamp:96,rivers:91,forests:67,settlements:22},['#829783','#465e4b','#677f78']),
 'Mountain Realm':preset('Каменные моря, снежные пики и крепости на высоких перевалах.',{landMass:76,mountains:98,temperature:34,forests:34,swamp:5,rivers:62},['#a9aa96','#737d73','#77908c']),
 'Forest Kingdom':preset('Бескрайние кроны, укромные поляны и священные деревья лесного народа.',{landMass:74,forests:97,humidity:82,mountains:34,fantasy:76,swamp:20},['#a1ac74','#38523a','#718982']),
 'Archipelago':preset('Островные королевства, каменные берега и проливы неизвестного моря.',{landMass:37,islands:96,mountains:53,temperature:68,rivers:38,roads:37},['#b6b88a','#628066','#3f737d']),
 'Wasteland':preset('Выжженные плато, сухие долины и одинокие огни среди камней.',{landMass:81,humidity:9,temperature:89,forests:6,swamp:0,rivers:14,settlements:17,ruins:67,corruption:24},['#b6a578','#8a7c60','#737e77']),
 'Ruined Empire':preset('Заросшие дороги соединяют осколки империи и безмолвные святилища.',{landMass:75,ruins:97,settlements:20,roads:94,forests:61,fantasy:53,corruption:32},['#a3976b','#6d7150','#68827c']),
 'Cursed Realm':preset('Мёртвые чащи, расколотая земля и порталы за пределы мира.',{corruption:97,fantasy:98,ruins:87,settlements:12,forests:65,temperature:29,mountains:77,humidity:61},['#817b75','#454b43','#5c777b'])},
 styles:{classic:{name:'Древний атлас',saturation:1,exposure:1,ocean:[37,76,85],paper:'#dfd5ad'},nocturne:{name:'Сумеречное королевство',saturation:.8,exposure:.87,ocean:[29,58,68],paper:'#ded0a4'},parchment:{name:'Летопись странника',saturation:.56,exposure:1.09,ocean:[100,119,114],paper:'#eee0bb'}},
 tools:[['select','cursor','Выбор'],['pan','move','Перемещение'],['terrain','terrain','Terrain Brush'],['height','height','Height Brush'],['mountain','mountain','Mountain Brush'],['forest','tree','Forest Brush'],['water','water','Water Brush'],['river','river','River Tool'],['road','road','Road Tool'],['biome','biome','Biome Paint'],['object','castle','Object Placement'],['label','label','Подписи'],['eraser','eraser','Eraser']],
 names:{regions:['ЭЛДЕРМАР','ВЕЙРНХОЛЬД','ТИХИЕ ЗЕМЛИ','СЕВЕРНЫЙ ПРЕДЕЛ','ПЕПЕЛЬНЫЙ КРАЙ','МОРВЕН','АРДЕНВЕЛЬ'],settlements:['Воронья стража','Эльденбург','Серебряный приют','Сосновая застава','Тихий берег','Замок Рассвета','Старый Арден','Огни Вейрна','Каменный предел','Лунная гавань'],landmarks:['Память королей','Круг забвения','Последний свет','Спящий исполин','Врата вечности','Безмолвный храм','Падший венец','Слёзы мира','Оплот странников','Гробница чародея','Лунный камень','Старая обитель','Трон без короля','Разбитый обелиск','Дозор вечности','Приют паломников','Колодец снов','Башня пепла','Сумеречный бастион','Святилище ветров'],rivers:['Серебрянка','Вейра','Морвен','Тихая','Эллен','Серая вода','Айрин','Лунная','Нерва','Хладная','Арден','Рунная','Велена','Северная','Ольха','Быстрая','Туманная','Воронья','Родниковая','Дальняя']}
 };
})(WS);
