(function(W){
 const entries=new Map(),images=new Map();let db=null;
 const validData=s=>typeof s==='string'&&s.length<7000000&&/^data:image\/(png|webp);base64,[A-Za-z0-9+/]+=*$/.test(s);
 function validate(list){if(list===undefined)return [];if(!Array.isArray(list)||list.length>100||JSON.stringify(list).length>30000000)throw Error('Библиотека превышает 100 объектов или 30 МБ');for(const d of list){if(!d||!/^custom-[a-z0-9-]{1,80}$/.test(d.id)||!validData(d.dataURL)||typeof d.name!=='string'||!d.name.trim()||d.name.length>120||typeof d.category!=='string'||d.category.length>80||typeof d.description!=='string'||!Array.isArray(d.tags)||d.tags.some(t=>typeof t!=='string')||!Number.isFinite(d.size)||d.size<8||d.size>500||!d.anchor||[d.anchor.x,d.anchor.y].some(v=>!Number.isFinite(v)||v<0||v>1)||!Number.isFinite(d.pixelWidth)||!Number.isFinite(d.pixelHeight)||d.pixelWidth<1||d.pixelHeight<1||d.pixelWidth>4096||d.pixelHeight>4096)throw Error('Некорректный пользовательский ассет');}if(new Set(list.map(d=>d.id)).size!==list.length)throw Error('Повторяющийся id ассета');return list;}
 function register(d){W.config.objects[d.id]={...d,type:d.id,custom:true,assetKind:'image2d',icon:'◇',layer:'POI',assetPath:'embedded:'+d.id,previewPath:'embedded:'+d.id,recommendedSize:{width:d.pixelWidth,height:d.pixelHeight},scaleRange:[.25,3],placementRules:{manualOnly:true},rarity:0,biomeAffinity:[]};if(!images.has(d.dataURL)){const im=new Image();images.set(d.dataURL,im);im.src=d.dataURL;}}
 async function prepare(list){validate(list);for(const d of list||[])if(!images.has(d.dataURL)){const im=new Image();images.set(d.dataURL,im);im.src=d.dataURL;}await Promise.all((list||[]).map(async d=>{const im=images.get(d.dataURL);await im.decode();if(im.naturalWidth!==d.pixelWidth||im.naturalHeight!==d.pixelHeight)throw Error('Размеры изображения не совпадают с метаданными');}));for(const d of list||[])register(d);}
 async function persist(){if(!db)throw Error('Хранилище браузера недоступно. Объекты сохранены в текущем проекте — используйте Save.');return new Promise((resolve,reject)=>{const tx=db.transaction('library','readwrite');tx.objectStore('library').put([...entries.values()],'items');tx.objectStore('library').put(W.config.categories,'categories');tx.oncomplete=resolve;tx.onerror=()=>reject(Error('Не удалось записать библиотеку. Сохраните проект через Save.'));});}
 function attach(p){p.customAssets=p.customAssets||[];const used=new Set(p.customAssets.map(d=>d.id));for(const d of entries.values())if(!used.has(d.id))p.customAssets.push(structuredClone(d));p.customCategories={...W.config.categories};}
 function activate(p){for(const d of p.customAssets||[])register(d);if(p.customCategories)for(const [k,v]of Object.entries(p.customCategories))if(/^user-[a-z0-9-]+$/.test(k)&&typeof v==='string')W.config.categories[k]=v;}
 W.custom={entries,images,validate,prepare,attach,activate,validData,async put(d,p){validate([d]);const all=[...entries.values()].filter(x=>x.id!==d.id).concat(d);validate(all);await prepare([d]);entries.set(d.id,d);if(p){p.customAssets=(p.customAssets||[]).filter(x=>x.id!==d.id).concat(structuredClone(d));attach(p);}await persist();},async remove(id){entries.delete(id);await persist();},persist,
 draw(c,def,x,y,size,rotation=0){const im=images.get(def.dataURL);if(!im?.complete||!im.naturalWidth)return false;if(W.assets?.drawRaster)return W.assets.drawRaster(c,im,def.dataURL,x,y,size,def.anchor,rotation);const h=size*def.pixelHeight/def.pixelWidth;c.save();c.translate(x,y);c.rotate(rotation*Math.PI/180);c.drawImage(im,-size*def.anchor.x,-h*def.anchor.y,size,h);c.restore();return true;},
 ready:new Promise(resolve=>{if(typeof indexedDB==='undefined'){resolve();return;}const req=indexedDB.open('worldsmith-assets',1);req.onupgradeneeded=()=>req.result.createObjectStore('library');req.onerror=()=>resolve();req.onsuccess=()=>{db=req.result;const tx=db.transaction('library','readonly'),r=tx.objectStore('library').get('items'),cats=tx.objectStore('library').get('categories');cats.onsuccess=()=>{for(const [k,v]of Object.entries(cats.result||{}))if(/^user-[a-z0-9-]+$/.test(k)&&typeof v==='string')W.config.categories[k]=v;};r.onsuccess=async()=>{try{validate(r.result||[]);for(const d of r.result||[])entries.set(d.id,d);await prepare(r.result||[]);}catch(e){console.warn(e.message);}resolve();};r.onerror=()=>resolve();};})};
})(WS);
