(function(W){
 const tileSize=512;
 function affectedTiles(bounds,level,padding=0){const r=W.semantic.expand(bounds,padding),x0=Math.max(0,Math.floor(r.x*level.resolution/tileSize)),y0=Math.max(0,Math.floor(r.y*level.resolution/tileSize)),x1=Math.min(level.columns-1,Math.ceil((r.x+r.width)*level.resolution/tileSize)-1),y1=Math.min(level.rows-1,Math.ceil((r.y+r.height)*level.resolution/tileSize)-1),out=[];for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++)out.push({x,y});return out;}
 function manifest(p,options={}){const dpr=options.dpr??2,maxZoom=options.maxZoom??W.config.render.maxZoom,maxResolution=dpr*maxZoom;if(!Number.isFinite(dpr)||dpr<1||dpr>3||!Number.isFinite(maxZoom)||maxZoom<1||maxZoom>W.config.render.maxZoom)throw Error('Unsupported pyramid profile');const levels=[];let resolution=Math.min(1,tileSize/Math.max(p.width,p.height));while(true){const width=Math.ceil(p.width*resolution),height=Math.ceil(p.height*resolution);levels.push({level:levels.length,resolution,semanticZoom:Math.min(maxZoom,Math.max(1,resolution/dpr)),width,height,columns:Math.ceil(width/tileSize),rows:Math.ceil(height/tileSize)});if(resolution===maxResolution)break;resolution=Math.min(maxResolution,resolution*2);}
  return{format:'worldsmith/deep-zoom/v1',renderModel:'atlas-v6',coordinateSystem:'world pixels; origin top-left; x right; y down (not geographic longitude/latitude)',extent:{width:p.width,height:p.height},tileSize,encoding:'image/webp',edgeTiles:'512 square, transparent padding beyond extent',detailModel:p.detailModel||{version:1,salt:'worldsmith'},profile:{dpr,maxZoom},levels,tileCount:levels.reduce((n,l)=>n+l.columns*l.rows,0),rasterLayers:p.layerOrder.filter(l=>l!=='Labels'&&p.layers[l].export),vectorLayers:['labels','pois','roads','rivers','regions'],rasterSplit:'Terrain, derived detail, roads, rivers and POI illustrations share raster tiles. Editable source geometry is also supplied separately. Labels and frame are not rasterized.',revision:options.revision??0,cache:{algorithm:2,key:'project SHA-256 / renderModel / detailModel / level / x / y',invalidationPadding:W.semantic.cfg.terrainPadding,objectPadding:W.semantic.cfg.editPadding},complete:false};
 }
 function vectors(p){const collection=features=>({type:'FeatureCollection',coordinateSystem:'world-pixels',features}),line=(r)=>({type:'Feature',id:r.id,properties:Object.fromEntries(Object.entries(r).filter(([k])=>k!=='points')),geometry:{type:'LineString',coordinates:r.points.map(pt=>[pt.x,pt.y])}}),borders=p.regions.map(()=>[]);
  for(let y=0;y<p.rows;y++)for(let x=0;x<p.cols;x++){const i=y*p.cols+x,id=p.regionMap[i];if(id<0)continue;const x0=x*5,y0=y*5,x1=Math.min(p.width,x0+5),y1=Math.min(p.height,y0+5);if(!x||p.regionMap[i-1]!==id)borders[id].push([[x0,y0],[x0,y1]]);if(x===p.cols-1||p.regionMap[i+1]!==id)borders[id].push([[x1,y0],[x1,y1]]);if(!y||p.regionMap[i-p.cols]!==id)borders[id].push([[x0,y0],[x1,y0]]);if(y===p.rows-1||p.regionMap[i+p.cols]!==id)borders[id].push([[x0,y1],[x1,y1]]);}
  return{'labels.json':p.labels,'pois.json':p.objects,'roads.geojson':collection(p.roads.map(line)),'rivers.geojson':collection(p.rivers.map(line)),'regions.geojson':collection(p.regions.map((r,i)=>({type:'Feature',id:r.id,properties:r,geometry:{type:'MultiLineString',coordinates:borders[i]}})))};
 }
 async function exportProject(project,writer,options={}){const p=W.storage.validate(structuredClone(project)),m=manifest(p,options),serialized=W.storage.json(p),bytes=new TextEncoder().encode(serialized),digest=await crypto.subtle.digest('SHA-256',bytes);m.projectHash=[...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,'0')).join('');m.coverage=options.bounds?{bounds:options.bounds,partial:true}:{partial:false};m.worstSourceRatio=0;m.sourceLimitedTiles=0;const json=v=>new Blob([JSON.stringify(v,null,2)],{type:'application/json'}),check=()=>{if(options.signal?.aborted)throw new DOMException('Экспорт отменён','AbortError');};
  // An incomplete manifest remains on disk after cancellation or failure.
  await writer('project.json',new Blob([serialized],{type:'application/json'}));await writer('map/manifest.json',json(m));await W.assets.ready;await W.custom.prepare(p.customAssets||[]);const service=new W.RenderService();let done=0;
  try{await service.setProject(p,1);const v=await service.request('vectors',{},0);for(const [name,data]of Object.entries(v.vectors)){check();await writer('vectors/'+name,json(data));}const overview=await service.request('webpTile',{semanticZoom:1,resolution:Math.min(512/p.width,512/p.height),rect:{x:0,y:0,width:p.width,height:p.height},overview:true},0);await writer('map/overview.webp',overview.blob);
   const tasks=m.levels.map(l=>({level:l,tiles:affectedTiles(options.bounds||{x:0,y:0,width:p.width,height:p.height},l)})),total=tasks.reduce((n,t)=>n+t.tiles.length,0);m.exportedTileCount=total;
   for(const {level:l,tiles}of tasks)for(const {x,y}of tiles){check();const result=await service.request('webpTile',{semanticZoom:l.semanticZoom,resolution:l.resolution,rect:{x:x*tileSize/l.resolution,y:y*tileSize/l.resolution,width:tileSize/l.resolution,height:tileSize/l.resolution}},0);check();if(result.blob.type!=='image/webp')throw Error('WebP encoding unavailable');await writer('map/tiles/'+l.level+'/'+x+'/'+y+'.webp',result.blob);m.worstSourceRatio=Math.max(m.worstSourceRatio,result.semantic.worstSourceRatio);if(result.semantic.sourceLimited)m.sourceLimitedTiles++;options.progress?.({done:++done,total,level:l.level});}
   m.complete=true;await writer('map/manifest.json',json(m));return m;
  }finally{service.dispose();}
 }
 function directoryWriter(root){return async(file,blob)=>{const parts=file.split('/');let dir=root;for(const part of parts.slice(0,-1))dir=await dir.getDirectoryHandle(part,{create:true});const handle=await dir.getFileHandle(parts.at(-1),{create:true}),stream=await handle.createWritable();try{await stream.write(blob);await stream.close();}catch(e){await stream.abort();throw e;}};}
 W.deepZoom={manifest,affectedTiles,vectors,exportProject,directoryWriter};
})(WS);
