(function(W){
 const $=id=>document.getElementById(id),ed=W.app.editor,section=document.createElement('section');section.className='quality-section';section.innerHTML='<div class="section-heading"><h2>Чёткость и детализация</h2><span>04</span></div><label>Editor Preview Quality<select id="preview-quality"><option>Performance</option><option selected>Balanced</option><option>Ultra</option></select></label><label>Label Quality<select id="label-quality"><option>Standard</option><option selected>High</option></select></label><label>Texture Detail<select id="texture-detail"><option>Low</option><option selected>Medium</option><option>High</option></select></label><div class="pair"><button id="zoom-50">50%</button><button id="zoom-100">100%</button><button id="zoom-150">150%</button><button id="zoom-200">200%</button></div><p id="quality-status" class="quality-status"></p><p class="tiny-note">Performance и Balanced сохраняют DPR экрана. Ultra добавляет суперсэмплинг. Камера использует готовые чанки, уточнение выполняется в Worker. Подписи остаются векторными; земля перерисовывается тайлами нужного LOD. При увеличении выше разрешения исходного PNG детали не могут восстановиться.</p>';$('panel-styling').append(section);
 for(const [id,key]of [['preview-quality','quality'],['label-quality','labels'],['texture-detail','texture']])$(id).onchange=()=>{ed.previewQuality[key]=$(id).value;try{localStorage.setItem('worldsmith-render-quality',JSON.stringify(ed.previewQuality));}catch{}ed.view?.request();};
 try{const saved=JSON.parse(localStorage.getItem('worldsmith-render-quality'));for(const [id,key]of [['preview-quality','quality'],['label-quality','labels'],['texture-detail','texture']])if(saved&&[...$(id).options].some(o=>o.value===saved[key])){$(id).value=saved[key];ed.previewQuality[key]=saved[key];}}catch{}
 for(const zoom of [50,100,150,200])$('zoom-'+zoom).onclick=()=>ed.zoomAt(zoom/100/ed.zoom);$('zoom-label').title='Нажмите для масштаба 100%';$('zoom-label').style.cursor='pointer';$('zoom-label').onclick=()=>ed.zoomAt(1/ed.zoom);
 const exportOptions=document.createElement('div');exportOptions.innerHTML='<label>Export Resolution<select id="export-resolution"><option value="native">Размер проекта</option><option value="2048">2K · длинная сторона 2048 px</option><option value="4096">4K · длинная сторона 4096 px</option><option value="8192">8K · длинная сторона 8192 px</option></select></label><p id="export-pixels" class="tiny-note"></p><p id="export-progress" role="status" class="quality-status"></p>';$('png').before(exportOptions);function dimensions(){const p=ed.project;if(!p)return;const side=Number($('export-resolution').value)||Math.max(p.width,p.height),scale=side/Math.max(p.width,p.height);$('export-pixels').textContent=`${Math.round(p.width*scale)} × ${Math.round(p.height*scale)} px · пропорции карты сохранены`;} $('export-resolution').onchange=dimensions;
 const oldExport=$('export').onclick;$('export').onclick=()=>{oldExport();dimensions();$('export-progress').textContent='';};
 $('png').onclick=async()=>{const button=$('png');button.disabled=true;$('json').disabled=true;try{await W.storage.png(ed.project,{labels:$('export-labels').checked,frame:$('export-frame').checked,longEdge:Number($('export-resolution').value)||undefined,textureDetail:ed.previewQuality.texture,progress:value=>$('export-progress').textContent='Рендер PNG · '+value+'%'});$('export-dialog').close();W.ui.toast('PNG готов: карта перерисована в выбранном разрешении');}catch(error){$('export-progress').textContent=error.message;}finally{button.disabled=false;$('json').disabled=false;}};
 const sourceNote=document.createElement('p');sourceNote.id='object-source-quality';sourceNote.className='quality-status';$('apply-object').before(sourceNote);function sourceQuality(){const o=ed.selected();if(!o||o.kind)return;const d=W.config.objects[o.type],native=d.custom?d.pixelWidth:W.assets.nativeResolution(d.sprite),pixels=d.size*(o.scale||1)*ed.zoom*(ed.view?.metrics?.backingScale||window.devicePixelRatio||1);sourceNote.textContent=native?(W.settlement?.kind(o)&&W.semantic.weights(ed.zoom).hierarchy>0?'Составная детализация; макро-исходник: ':'Исходник: ')+Math.round(native)+' px · объект на экране: '+Math.round(pixels)+' px'+(pixels>native?' · предел детализации исходного изображения':' · исходного разрешения достаточно'):'Векторный / процедурный объект';sourceNote.style.color=pixels>native&&native?'#d6aa72':'';}const prior=ed.onChange;ed.onChange=(...args)=>{prior?.(...args);sourceQuality();};
 W.qualityUI={status(m){sourceQuality();$('quality-status').textContent=`${Math.round(m.zoom*100)}% · DPR ${m.dpr} · canvas ${m.width}×${m.height} px · Terrain LOD ${m.terrain?.lod??1}× · ${m.semantic?.band||'overview'} · детали ${m.semantic?.derived||0} · исходник ×${(m.semantic?.worstSourceRatio||0).toFixed(2)}${m.semantic?.sourceLimited?' · ⚠ предел исходников':''} · SVG labels`;} };
})(WS);
