(function(W){
 function validate(input){
  const fail=()=>{throw new Error('Файл повреждён или имеет неподдерживаемый формат');};
  if(!input||![1,2].includes(input.version)||!Number.isInteger(input.width)||!Number.isInteger(input.height)||input.width<300||input.height<300||input.width>W.config.maxSize||input.height>W.config.maxSize)fail();
  let p;try{p=W.model.migrate(input);}catch{fail();}
  if(!W.worldLayout.validate(p.worldLayout,p))fail();
  if(!p.detailModel||p.detailModel.version!==1||typeof p.detailModel.salt!=='string'||p.detailModel.salt.length>100)fail();for(const o of [...(p.objects||[]),...(p.labels||[])]){if(o.importance!==undefined&&(!Number.isFinite(o.importance)||o.importance<0||o.importance>100))fail();for(const k of ['minZoom','maxZoom'])if(o[k]!==undefined&&(!Number.isFinite(o[k])||o[k]<0||o[k]>64))fail();if((o.minZoom??0)>(o.maxZoom??64))fail();}W.custom?.validate(p.customAssets);const customIds=new Set((p.customAssets||[]).map(d=>d.id));
  const N=Math.ceil(p.width/5)*Math.ceil(p.height/5),point=a=>a&&Number.isFinite(a.x)&&Number.isFinite(a.y)&&a.x>=0&&a.y>=0&&a.x<=p.width&&a.y<=p.height;
  if(p.cellSize!==5||p.cols!==Math.ceil(p.width/5)||p.rows!==Math.ceil(p.height/5)||typeof p.seed!=='string'||typeof p.title!=='string'||!Number.isFinite(p.seaLevel)||p.seaLevel<=0||p.seaLevel>=1)fail();
  for(const key of ['terrain','temperature','humidity','forestDensity'])if(!Array.isArray(p[key])||p[key].length!==N||p[key].some(v=>!Number.isFinite(v)||v<0||v>1))fail();
  if(!Array.isArray(p.biomes)||p.biomes.length!==N||p.biomes.some(b=>b!=='water'&&!W.config.biomes[b]))fail();
  if(!W.config.presets[p.preset]||!p.params)fail();for(const k of Object.keys(W.config.parameters))if(!Number.isFinite(p.params[k])||p.params[k]<0||p.params[k]>100)fail();
  if(!p.layers||!Array.isArray(p.layerOrder)||p.layerOrder.length!==W.config.layers.length||new Set(p.layerOrder).size!==W.config.layers.length||p.layerOrder.some(l=>!W.config.layers.includes(l)))fail();for(const l of W.config.layers)if(!p.layers[l]||['visible','locked','export'].some(k=>typeof p.layers[l][k]!=='boolean'))fail();
  for(const key of ['rivers','roads'])if(!Array.isArray(p[key])||p[key].length>10000||p[key].some(v=>!Array.isArray(v.points)||v.points.length>N||!v.points.every(point)||!Number.isFinite(v.width)||v.width<=0||v.width>200))fail();
  if(!Array.isArray(p.regions)||p.regions.length>1000||p.regions.some(r=>!point(r.position)||typeof r.name!=='string'||typeof r.faction!=='string'||!/^#[0-9a-f]{6}$/i.test(r.color)))fail();
  if(!Array.isArray(p.regionMap)||p.regionMap.length!==N||p.regionMap.some(v=>!Number.isInteger(v)||v< -1||v>=p.regions.length))fail();
  if(!Array.isArray(p.objects)||p.objects.length>15000||p.objects.some(o=>(!W.config.objects[o.type]&&!customIds.has(o.type))||(o.type?.startsWith('custom-')&&!customIds.has(o.type))||!W.config.layers.includes(o.layer)||!point(o.position)||['id','name','description','icon','faction','region'].some(k=>typeof o[k]!=='string')||!Array.isArray(o.tags)||o.tags.some(t=>typeof t!=='string')||!o.properties||typeof o.properties!=='object'||Array.isArray(o.properties)||!/^#[0-9a-f]{6}$/i.test(o.color)||!Number.isFinite(o.variant)||(o.scale!==undefined&&(!Number.isFinite(o.scale)||o.scale<.25||o.scale>3))||(o.rotation!==undefined&&(!Number.isFinite(o.rotation)||Math.abs(o.rotation)>180))))fail();
  if(new Set(p.objects.map(o=>o.id)).size!==p.objects.length)fail();
  if(!Array.isArray(p.labels)||p.labels.length>15000||p.labels.some(l=>!point(l.position)||typeof l.text!=='string'||typeof l.id!=='string'||!Number.isFinite(l.size)||l.size<6||l.size>100||!Number.isFinite(l.rotation)||!/^#[0-9a-f]{6}$/i.test(l.color)))fail();
  if(!W.config.styles[p.styling?.theme]||['relief','texture','atmosphere'].some(k=>!Number.isFinite(p.styling[k])||p.styling[k]<0||p.styling[k]>100)||typeof p.styling.labels!=='boolean'||typeof p.styling.frame!=='boolean')fail();
  return p;
 }
 function json(p,game=false){const data=structuredClone(p);if(game)Object.assign(data,{schema:'worldsmith/game-map/v2',size:{width:p.width,height:p.height},coordinateSystem:'pixels; origin=top-left; x=right; y=down',heightData:p.terrain,poi:p.objects.filter(o=>o.layer!=='Decorations'),biomeDefinitions:W.config.biomes,objectDefinitions:Object.fromEntries(Object.entries(W.config.objects).map(([id,d])=>{const {dataURL,...definition}=d;return [id,definition];}))});return JSON.stringify(data);}
 function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
 function save(p,game=false){download(new Blob([json(p,game)],{type:'application/json'}),'worldsmith-'+p.seed.replace(/[^a-z0-9_-]/gi,'_').slice(0,50)+(game?'.map.json':'.world.json'));}
 async function png(p,options={}){p=structuredClone(p);await W.assets.ready;await document.fonts.ready;await W.custom?.prepare(p.customAssets||[]);const edge=options.longEdge||Math.max(p.width,p.height);if(!Number.isFinite(edge)||edge<300||edge>W.config.render.export.maxEdge)throw Error('Экспорт поддерживает длинную сторону до 8192 px');const scale=edge/Math.max(p.width,p.height),width=Math.round(p.width*scale),height=Math.round(p.height*scale),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d'),service=new W.RenderService(),bandSize=W.config.render.export.bandPixels;try{await service.setProject(p,1);for(let y=0;y<height;y+=bandSize){const h=Math.min(bandSize,height-y),r=await service.request('exportBand',{semanticZoom:options.semanticZoom??Math.min(W.config.render.maxZoom,Math.max(1,scale)),resolution:scale,rect:{x:0,y:y/scale,width:width/scale,height:h/scale},labels:options.labels??p.styling.labels,frame:options.frame??p.styling.frame,texture:options.textureDetail||'Medium'},10);ctx.drawImage(r.image,0,y);r.image.close();options.progress?.(Math.round((y+h)/height*100));}}finally{service.dispose();}return new Promise((resolve,reject)=>canvas.toBlob(b=>{if(!b){reject(new Error('Не удалось создать PNG'));return;}download(b,'worldsmith-atlas-'+width+'x'+height+'.png');canvas.width=1;canvas.height=1;resolve(b);},'image/png'));}
 W.storage={validate,json,download,save,png,async load(file){if(file.size>70e6)throw new Error('Размер файла превышает 70 МБ');const p=validate(JSON.parse(await file.text()));await W.custom?.prepare(p.customAssets||[]);W.custom?.activate(p);return p;}};
})(WS);
