(function(W){
 const states=new WeakMap(),clamp=W.model.clamp,cfg=W.config.render.terrain,P=cfg.tilePixels,levels=cfg.lodLevels;
 const rgb=h=>[1,3,5].map(k=>parseInt(h.slice(k,k+2),16));
 function update(p,s,r){const C=p.cols,R=p.rows,colors=s.colors,at=(x,y)=>p.terrain[clamp(y,0,R-1)*C+clamp(x,0,C-1)];for(let y=Math.max(0,Math.floor(r.y/5)-5);y<Math.min(R,Math.ceil((r.y+r.height)/5)+5);y++)for(let x=Math.max(0,Math.floor(r.x/5)-5);x<Math.min(C,Math.ceil((r.x+r.width)/5)+5);x++){const i=y*C+x;let red=0,green=0,blue=0,weight=0;for(let yy=-2;yy<=2;yy++)for(let xx=-2;xx<=2;xx++){const j=clamp(y+yy,0,R-1)*C+clamp(x+xx,0,C-1);if(p.terrain[j]<p.seaLevel)continue;const f=1/(1+xx*xx+yy*yy),col=colors[p.biomes[j]]||colors.plain;red+=col[0]*f;green+=col[1]*f;blue+=col[2]*f;weight+=f;}s.field[i*3]=weight?red/weight:colors.coast[0];s.field[i*3+1]=weight?green/weight:colors.coast[1];s.field[i*3+2]=weight?blue/weight:colors.coast[2];const dx=at(x+1,y)-at(x-1,y),dy=at(x,y+1)-at(x,y-1),curve=at(x+4,y)+at(x-4,y)+at(x,y+4)+at(x,y-4)-4*p.terrain[i];s.light[i]=clamp((-dx*.8-dy)*660,-34,34)-clamp(-curve*70,-8,10);}s.elevations=W.surface.heightField(p);s.distance=W.coast.distance(p);}
 function state(p){let s=states.get(p);if(s)return s;s={colors:Object.fromEntries(Object.entries(W.config.biomes).map(([k,v])=>[k,rgb(v.color)])),field:new Float32Array(p.terrain.length*3),light:new Float32Array(p.terrain.length),noise:W.random.noise(p.seed+'surface-v5'),tiles:new Map(),hits:0,misses:0};update(p,s,{x:0,y:0,width:p.width,height:p.height});states.set(p,s);return s;}
 function sample(a,C,ix,iy,jx,jy,u,v,stride=1,channel=0){const top=a[(iy*C+ix)*stride+channel]*(1-u)+a[(iy*C+jx)*stride+channel]*u,bot=a[(jy*C+ix)*stride+channel]*(1-u)+a[(jy*C+jx)*stride+channel]*u;return top*(1-v)+bot*v;}
 function tile(p,s,tx,ty,lod,on,detail){const style=W.config.styles[p.styling.theme],key=[tx,ty,lod,p.styling.theme,p.styling.relief,p.styling.texture,on('Terrain'),on('Height'),on('Water'),detail].join('|');if(s.tiles.has(key)){const v=s.tiles.get(key);s.tiles.delete(key);s.tiles.set(key,v);s.hits++;return v;}s.misses++;const size=P+2,canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const c=canvas.getContext('2d'),im=c.createImageData(size,size),wi=c.createImageData(size,size),hi=c.createImageData(size,size),n=s.noise,sea=p.seaLevel,t=p.styling.texture/100,relief=p.styling.relief/100,amount={Low:.45,Medium:.75,High:1}[detail]??.75,C=p.cols,R=p.rows;
 for(let y=0;y<size;y++)for(let x=0;x<size;x++){const wx=(tx*P+x-1+.5)/lod,wy=(ty*P+y-1+.5)/lod,gx=clamp(wx/5-.5,0,C-1),gy=clamp(wy/5-.5,0,R-1),ix=Math.floor(gx),iy=Math.floor(gy),jx=Math.min(ix+1,C-1),jy=Math.min(iy+1,R-1),u=gx-ix,v=gy-iy;let e=sample(s.elevations,C,ix,iy,jx,jy,u,v);const shore=sample(s.distance,C,ix,iy,jx,jy,u,v),patch=n(wx*.0235,wy*.0235)-.5,medium=n(wx*.105+100,wy*.105)-.5,grain=n(wx*.53,wy*.53)-.5;
 // Shared world-space shore perturbation. Both sides use exactly the same boundary.
 e+=(medium*.0015+grain*.0005)*clamp(1-Math.abs(e-sea)/.035);const water=e<sea,o=(y*size+x)*4;let r,g,b,shade;
 if(water){const deep=clamp(shore/125)*.65+clamp((sea-e)*6)*.35,a=Math.pow(deep,.6);r=100+(style.ocean[0]-100)*a;g=139+(style.ocean[1]-139)*a;b=133+(style.ocean[2]-133)*a;shade=patch*10+medium*1.5+grain*.8;const foam=clamp(1-Math.abs(e-sea)/.0012)*(.15+clamp(patch+.4)*.35);r+=(189-r)*foam;g+=(205-g)*foam;b+=(176-b)*foam;if(!on('Water')){r=27;g=36;b=34;} }
 else{r=sample(s.field,C,ix,iy,jx,jy,u,v,3,0);g=sample(s.field,C,ix,iy,jx,jy,u,v,3,1);b=sample(s.field,C,ix,iy,jx,jy,u,v,3,2);if(!on('Terrain')){r=76;g=84;b=71;}const moisture=sample(p.humidity,C,ix,iy,jx,jy,u,v),a=clamp(patch+.25)*.2*t;r+=(116-r)*a;g+=(moisture>.55?136-g:121-g)*a;b+=(moisture>.55?75-b:66-b)*a;shade=(grain*8*amount+medium*9+patch*22)*t;if(lod>=1)shade+=(n(wx*1.7,wy*1.7)-.5)*2.5*t*amount;const coastal=clamp(1-(e-sea)/.018)*(.25+patch*.14);r+=(160-r)*coastal;g+=(151-g)*coastal;b+=(109-b)*coastal;}
 const gray=r*.3+g*.59+b*.11,red=clamp((gray+(r-gray)*style.saturation)*style.exposure+shade,0,255),green=clamp((gray+(g-gray)*style.saturation)*style.exposure+shade,0,255),blue=clamp((gray+(b-gray)*style.saturation)*style.exposure+shade,0,255);const target=water?wi.data:im.data;target[o]=red;target[o+1]=green;target[o+2]=blue;target[o+3]=255;
 if(!water&&on('Height')){const light=sample(s.light,C,ix,iy,jx,jy,u,v)*relief,value=light>0?255:0,brightness=red*.3+green*.59+blue*.11;hi.data[o]=hi.data[o+1]=hi.data[o+2]=value;hi.data[o+3]=clamp(Math.abs(light)/Math.max(20,light>0?255-brightness:brightness),0,.55)*255;}}
 c.putImageData(im,0,0);const water=document.createElement('canvas'),height=document.createElement('canvas');for(const v of [water,height]){v.width=size;v.height=size;}water.getContext('2d').putImageData(wi,0,0);height.getContext('2d').putImageData(hi,0,0);const out={Base:canvas,Water:water,Height:height,rect:{x:tx*P/lod,y:ty*P/lod,width:P/lod,height:P/lod}};s.tiles.set(key,out);while(s.tiles.size>cfg.maxTiles)s.tiles.delete(s.tiles.keys().next().value);return out;}
 function render(p,c,mode,on,fallback,options={}){if(!['Atlas','Editor'].includes(mode)){fallback(p,c,mode,on);return;}const s=state(p),r=options.rect||{x:0,y:0,width:p.width,height:p.height},scale=options.resolution||1,lod=levels.find(v=>v>=scale)||48,world=P/lod,x0=Math.max(0,Math.floor(r.x/world)),y0=Math.max(0,Math.floor(r.y/world)),x1=Math.min(Math.ceil(p.width/world),Math.ceil((r.x+r.width)/world)),y1=Math.min(Math.ceil(p.height/world),Math.ceil((r.y+r.height)/world));for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){const im=tile(p,s,x,y,lod,on,options.textureDetail||'Medium')[options.surfaceLayer||'Base'];c.drawImage(im,1,1,P,P,x*world,y*world,world,world);}W.terrainTiles.last={lod,visibleTiles:Math.max(0,(x1-x0)*(y1-y0)),cachedTiles:s.tiles.size,hits:s.hits,misses:s.misses,cacheBytes:s.tiles.size*(P+2)**2*12};}
 W.terrainTiles={render,state,levels,tilePixels:P,maxTiles:cfg.maxTiles,last:null,invalidate(p,r){const s=states.get(p);if(!r||!s){states.delete(p);return;}update(p,s,r);for(const [key,t]of s.tiles)if(W.scene.intersects(t.rect,{x:r.x-(r.padding??190),y:r.y-(r.padding??190),width:r.width+2*(r.padding??190),height:r.height+2*(r.padding??190)}))s.tiles.delete(key);}};const previous=W.surface.invalidate;W.surface.invalidate=(p,r)=>{previous(p,r);if(!r||r.padding===undefined||r.padding>=190)W.coast?.invalidate(p);W.terrainTiles.invalidate(p,r);W.scene?.invalidate(p,r);W.detail?.invalidate(p,r);};W.surface.render=render;
})(WS);
