(function(W){
 const $=id=>document.getElementById(id),cfg=W.config;let preset='Dark Fantasy',params={...cfg.presets[preset].params},toastTimer,generating=false,worker=null,minimapImage=null;
 function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3800);}W.ui={toast};
 function iconize(root=document){root.querySelectorAll('[data-icon]').forEach(b=>{b.insertAdjacentHTML('afterbegin',W.icon(b.dataset.icon));b.removeAttribute('data-icon');});}iconize();
 function options(el,items){el.replaceChildren();for(const [value,text]of items){const o=document.createElement('option');o.value=value;o.textContent=text;el.append(o);}}
 function slider(parent,id,label,value,onInput,min=0,max=100,suffix='%'){const l=document.createElement('label');l.className='slider-label';l.textContent=label;const out=document.createElement('output');out.id=id+'-value';out.textContent=value+suffix;const input=document.createElement('input');Object.assign(input,{type:'range',min,max,value,id});input.setAttribute('aria-label',label);input.oninput=()=>{out.textContent=input.value+suffix;onInput(Number(input.value));};l.append(out,input);parent.append(l);}
 function setTab(name){document.querySelector('.panel-scroll').scrollTop=0;document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!=='panel-'+name);document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===name);b.setAttribute('aria-selected',String(b.dataset.tab===name));});}
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
 const editor=new W.Editor($('map'),$('overlay'),$('viewport'),refresh);W.app={editor,tool,refresh};
 for(const [key,label]of Object.entries(cfg.parameters))slider($('parameters'),'param-'+key,label,params[key],v=>params[key]=v);
 for(const [key,label,value,min,max,suffix]of [['radius','Радиус кисти',50,5,200,' px'],['intensity','Интенсивность',55,5,100,'%'],['hardness','Жёсткость',35,0,95,'%'],['density','Плотность',80,5,100,'%'],['randomization','Вариативность',35,0,100,'%']])slider($('brush-controls'),'brush-'+key,label,value,v=>editor[key]=key==='radius'?v:v/100,min,max,suffix);
 for(const [key,label,value]of [['relief','Глубина рельефа',65],['texture','Фактура поверхности',55],['atmosphere','Дымка и атмосфера',40]])slider($('style-controls'),'style-'+key,label,value,()=>{});
 options($('biome'),Object.entries(cfg.biomes).map(([id,d])=>[id,d.name]));$('biome').value='forest';options($('erase-layer'),cfg.layers.map(l=>[l,l]));$('erase-layer').value='Vegetation';options($('object-type'),Object.entries(cfg.objects).map(([id,d])=>[id,d.name]));options($('theme'),Object.entries(cfg.styles).map(([id,d])=>[id,d.name]));
 $('biome').onchange=e=>editor.biome=e.target.value;$('height-direction').onchange=e=>editor.heightDirection=Number(e.target.value);$('road-kind').onchange=e=>editor.roadKind=e.target.value;$('erase-layer').onchange=e=>editor.eraseLayer=e.target.value;
 const hints={select:'Нажмите на объект, чтобы раскрыть его историю',pan:'Перетаскивайте карту',terrain:'Рисуйте новые берега и участки суши',height:'Поднимайте хребты и углубляйте долины',mountain:'Рисуйте горные цепи',forest:'Создавайте чащи и редколесье',water:'Рисуйте озёра, моря и проливы',river:'Проведите извилистое русло',road:'Проложите дорогу между поселениями',object:'Выберите место на карте',biome:'Меняйте характер ландшафта',label:'Перетащите подпись или нажмите для новой',eraser:'Удаляйте детали выбранного слоя'};
 function tool(id){editor.tool=id;document.querySelectorAll('[data-tool]').forEach(b=>{b.classList.toggle('active',b.dataset.tool===id);b.setAttribute('aria-pressed',String(b.dataset.tool===id));});const def=cfg.tools.find(t=>t[0]===id);$('active-tool').textContent=def[2];$('hint').textContent=hints[id];$('brush-title').textContent=def[2];$('brush-description').textContent=hints[id];$('viewport').style.cursor=id==='pan'?'grab':id==='select'?'default':'crosshair';if(!['select','pan'].includes(id))setTab(['object','label'].includes(id)?'objects':'brush');}
 for(const [id,icon,label]of cfg.tools){const b=document.createElement('button');b.className='tool'+(id==='select'?' active':'');b.innerHTML=W.icon(icon,20);b.title=label;b.setAttribute('aria-label',label);b.dataset.tool=id;b.onclick=()=>tool(id);$('tools').append(b);}
 function syncParams(){for(const k of Object.keys(cfg.parameters)){$('param-'+k).value=params[k];$('param-'+k+'-value').textContent=params[k]+'%';}$('preset-name').textContent=preset;$('preset-description').textContent=cfg.presets[preset].description;const thumb=thumbnails.get(preset);if(thumb){const c=$('preset-preview').getContext('2d');c.drawImage(thumb,0,0,520,240);}}
 function syncStyle(){const p=editor.project;$('map-title').value=p.title;$('map-subtitle').value=p.subtitle;$('theme').value=p.styling.theme;$('show-labels').checked=p.styling.labels;$('show-frame').checked=p.styling.frame;for(const k of ['relief','texture','atmosphere']){$('style-'+k).value=p.styling[k];$('style-'+k+'-value').textContent=p.styling[k]+'%';}}
 function syncProject(){const p=editor.project;preset=p.preset;params={...p.params};$('seed').value=p.seed;const size=Object.entries(cfg.sizes).find(([,d])=>d[0]===p.width&&d[1]===p.height);$('size').value=size?.[0]||'Custom';$('width').value=p.width;$('height').value=p.height;$('dimensions').hidden=$('size').value!=='Custom';syncParams();syncStyle();}
 function refresh(ed,kind='data'){
  if(!ed.project)return;const p=ed.project;$('zoom-label').textContent=Math.round(ed.zoom*100)+'%';if(kind==='view')return;
  $('undo').disabled=!ed.history.length;$('redo').disabled=!ed.future.length;$('dirty').hidden=!ed.dirty;$('stats').textContent=`${p.width} × ${p.height}  ·  ${p.objects.filter(o=>o.layer!=='Decorations').length} мест  ·  ${p.regions.length} земель`;$('world-title').textContent=p.title;$('world-subtitle').textContent=p.subtitle;$('preset-tag').textContent=p.preset.toUpperCase();
  if(kind==='project')syncProject();renderLayers();const obj=ed.selected(),label=obj?.kind;
  $('object-inspector').hidden=!obj||!!label;$('label-inspector').hidden=!label;$('object-empty').hidden=!!obj;
  if(obj&&label){$('label-text').value=obj.text;$('label-size').value=obj.size;$('label-rotation').value=obj.rotation;$('label-color').value=obj.color;}
  else if(obj){$('selected-caption').textContent=cfg.objects[obj.type].name;$('object-name').value=obj.name;$('object-type').value=obj.type;$('object-description').value=obj.description;$('object-icon').value=obj.icon;$('object-color').value=obj.color;$('object-faction').value=obj.faction;$('object-tags').value=obj.tags.join(', ');$('object-properties').value=JSON.stringify(obj.properties,null,2);$('object-x').value=Math.round(obj.position.x);$('object-y').value=Math.round(obj.position.y);options($('object-region'),[['','Без региона'],...p.regions.map(r=>[r.id,r.name])]);$('object-region').value=obj.region;const c=$('selected-preview').getContext('2d');c.clearRect(0,0,130,110);W.renderer.object(c,{...obj,position:{x:65,y:88}});}
  if(kind==='selection'&&obj)setTab('objects');
 }
 function renderLayers(){const p=editor.project;$('layers').replaceChildren();p.layerOrder.forEach((l,i)=>{const row=document.createElement('div');row.className='layer';const number=document.createElement('small');number.textContent=String(i+1).padStart(2,'0');const name=document.createElement('span');name.textContent=l;row.append(number,name);for(const [key,icon,title]of [['visible','eye','Видимость'],['locked','lock','Блокировка']]){const b=document.createElement('button');b.innerHTML=W.icon(icon);b.title=title+' · '+l;b.setAttribute('aria-label',b.title);b.className=key==='visible'&&!p.layers[l][key]?'off':key==='locked'&&p.layers[l][key]?'locked':'';b.setAttribute('aria-pressed',String(p.layers[l][key]));b.onclick=()=>{editor.snapshot();p.layers[l][key]=!p.layers[l][key];editor.draw();refresh(editor);};row.append(b);}const order=document.createElement('div');order.className='order';for(const [delta,label]of [[-1,'▴'],[1,'▾']]){const b=document.createElement('button');b.textContent=label;b.title=(delta<0?'Поднять ':'Опустить ')+l;b.setAttribute('aria-label',b.title);b.disabled=i+delta<0||i+delta>=p.layerOrder.length;b.onclick=()=>{editor.snapshot();[p.layerOrder[i],p.layerOrder[i+delta]]=[p.layerOrder[i+delta],p.layerOrder[i]];editor.draw();refresh(editor);};order.append(b);}row.append(order);$('layers').append(row);});}
 function updateMinimap(){if(!editor.project||$('minimap-wrap').hidden||!minimapImage)return;const c=$('minimap').getContext('2d'),w=190,h=126,p=editor.project;c.clearRect(0,0,w,h);c.drawImage(minimapImage,0,0,w,h);const sx=w/p.width,sy=h/p.height;c.strokeStyle='#f1d699';c.lineWidth=1;c.fillStyle='#f1d69912';const x=-editor.offset.x/editor.zoom*sx,y=-editor.offset.y/editor.zoom*sy,ww=editor.viewport.clientWidth/editor.zoom*sx,hh=editor.viewport.clientHeight/editor.zoom*sy;c.fillRect(x,y,ww,hh);c.strokeRect(x,y,ww,hh);}
 editor.onDraw=()=>{minimapImage??=document.createElement('canvas');minimapImage.width=190;minimapImage.height=126;minimapImage.getContext('2d').drawImage(editor.canvas,0,0,190,126);updateMinimap();};editor.onView=updateMinimap;
 $('minimap-toggle').onclick=()=>{$('minimap-wrap').hidden=!$('minimap-wrap').hidden;updateMinimap();};$('minimap').onclick=e=>{const r=e.target.getBoundingClientRect(),p=editor.project,x=(e.clientX-r.left)/r.width*p.width,y=(e.clientY-r.top)/r.height*p.height;editor.offset={x:editor.viewport.clientWidth/2-x*editor.zoom,y:editor.viewport.clientHeight/2-y*editor.zoom};editor.transform();};
 $('render-mode').onchange=e=>{editor.mode=e.target.value;editor.draw();$('legend').replaceChildren();$('legend').hidden=!['Biome','Height','Region'].includes(editor.mode);const entries=editor.mode==='Biome'?Object.values(cfg.biomes).map(b=>[b.name,b.color]):editor.mode==='Region'?editor.project.regions.map(r=>[r.name,r.color]):[['Низины','#557050'],['Предгорья','#8e9d79'],['Высокие вершины','#e1dfbf']];for(const [name,color]of entries){const d=document.createElement('div'),dot=document.createElement('i');dot.style.background=color;d.append(dot,document.createTextNode(name));$('legend').append(d);}};
 $('zoomout').onclick=()=>editor.zoomAt(.8);$('zoomin').onclick=()=>editor.zoomAt(1.25);$('fit').onclick=()=>editor.fit();$('undo').onclick=()=>editor.undo();$('redo').onclick=()=>editor.redo();$('size').onchange=()=>$('dimensions').hidden=$('size').value!=='Custom';
 function randomSeed(){$('seed').value='REALM-'+crypto.getRandomValues(new Uint32Array(1))[0].toString(36).toUpperCase();}
 function progress(message,percent){$('progress-text').textContent=message;$('progress-fill').style.width=percent+'%';$('progress-percent').textContent=percent+'%';}
 async function generate(initial=false){if(generating)return;const dims=cfg.sizes[$('size').value]||[Number($('width').value),Number($('height').value)],seed=$('seed').value.trim();if(!seed||dims.some(v=>!Number.isInteger(v)||v<300||v>cfg.maxSize)){toast('Введите seed и размеры от 300 до 3200 px');return;}generating=true;editor.busy=true;$('busy').hidden=false;progress('Пробуждаем древние земли',3);$('generate').disabled=true;$('generate-side').disabled=true;
  try{
   document.querySelectorAll('.topbar nav button').forEach(b=>b.disabled=true);document.querySelector('.inspector').inert=true;
   await W.assets.ready;await W.custom?.ready;
   const args={seed,width:dims[0],height:dims[1],preset,params:{...params}};
   let p;
   if(location.protocol!=='file:')p=await new Promise((resolve,reject)=>{worker=new Worker('src/generator-worker.js');worker.onmessage=e=>{if(e.data.project){resolve(e.data.project);worker.terminate();worker=null;}else if(e.data.error){reject(new Error(e.data.error));worker.terminate();worker=null;}else progress(e.data.message,e.data.percent);};worker.onerror=e=>{reject(new Error(e.message));worker.terminate();worker=null;};worker.postMessage(args);});
   else{await new Promise(r=>setTimeout(r,25));p=W.generator.generate(seed,...dims,preset,params,progress);}
   if(editor.project)editor.snapshot();editor.mode='Atlas';$('render-mode').value='Atlas';$('legend').hidden=true;editor.setProject(p);progress('Собираем видимые чанки атласа',92);await editor.view.waitReady();editor.dirty=!initial;syncProject();refresh(editor);toast(initial?'Добро пожаловать в Элдермар':'Новый мир готов к вашей истории');
  }catch(err){toast('Не удалось создать мир: '+err.message);console.error(err);}finally{generating=false;editor.busy=false;$('busy').hidden=true;document.querySelectorAll('.topbar nav button').forEach(b=>b.disabled=false);document.querySelector('.inspector').inert=false;$('generate-side').disabled=false;refresh(editor);}
 }
 $('generate').onclick=()=>generate();$('generate-side').onclick=()=>generate();$('random').onclick=()=>{randomSeed();generate();};$('seed-dice').onclick=randomSeed;$('new').onclick=()=>{randomSeed();generate();};
 const thumbnails=new Map();
 async function buildThumbnails(){await W.assets.ready;for(const [name,def]of Object.entries(cfg.presets)){const result=await editor.view.service.request('thumbnail',{preset:name},-20),c=document.createElement('canvas');if(!result.image)continue;c.width=result.image.width;c.height=result.image.height;c.getContext('2d').drawImage(result.image,0,0);result.image.close();thumbnails.set(name,c);const b=document.createElement('button');b.className='preset-option';b.dataset.preset=name;const image=document.createElement('canvas');image.width=540;image.height=340;image.getContext('2d').drawImage(c,0,0);const desc=document.createElement('div');desc.className='description';const title=document.createElement('strong'),note=document.createElement('p');title.textContent=name;note.textContent=def.description;desc.append(title,note);b.append(image,desc);b.onclick=()=>{preset=name;params={...def.params};syncParams();$('preset-dialog').close();setTab('generator');toast('Пресет выбран. Нажмите Generate, чтобы создать мир.');};$('preset-grid').append(b);if(name===preset)syncParams();await new Promise(r=>setTimeout(r,0));}}
 function openPresets(){document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('active',b.dataset.preset===preset));$('preset-dialog').showModal();}$('presets').onclick=openPresets;$('preset-card').onclick=openPresets;$('help').onclick=()=>$('help-dialog').showModal();
 async function library(){if(W.libraryUI){await W.libraryUI.refresh();return;}await W.assets.ready;for(const [type,def]of Object.entries(cfg.objects)){const b=document.createElement('button');b.className='object-tile';b.dataset.object=type;b.title=def.name;const canvas=document.createElement('canvas');canvas.width=100;canvas.height=86;const c=canvas.getContext('2d');if(def.sprite!==undefined)W.assets.draw(c,def.sprite,50,64,70);else W.renderer.object(c,{...W.objects.create(type,{x:50,y:54}),variant:.3});const label=document.createElement('span');label.textContent=def.name;b.append(canvas,label);b.onclick=()=>{editor.objectType=type;tool('object');document.querySelectorAll('[data-object]').forEach(t=>t.classList.toggle('active',t.dataset.object===type));toast(def.name+': выберите место на карте');};$('object-library').append(b);}$('object-count').textContent=Object.keys(cfg.objects).length;}
 $('apply-object').onclick=()=>{const o=editor.selected();if(!o||o.kind)return;const type=$('object-type').value;if(!editor.editable(o.layer)||!editor.editable(cfg.objects[type].layer)){toast('Слой скрыт или заблокирован');return;}let properties;try{properties=JSON.parse($('object-properties').value);if(!properties||typeof properties!=='object'||Array.isArray(properties))throw Error();}catch{toast('Свойства должны быть JSON-объектом: {"level": 5}');return;}const x=Number($('object-x').value),y=Number($('object-y').value);if(!Number.isFinite(x)||!Number.isFinite(y)||x<0||y<0||x>editor.project.width||y>editor.project.height){toast('Координаты должны находиться на карте');return;}editor.snapshot();const old={...o.position};Object.assign(o,{name:$('object-name').value.trim()||cfg.objects[type].name,type,description:$('object-description').value,icon:$('object-icon').value||cfg.objects[type].icon,position:{x,y},properties,layer:cfg.objects[type].layer,color:$('object-color').value,faction:$('object-faction').value,region:$('object-region').value,tags:$('object-tags').value.split(',').map(t=>t.trim()).filter(Boolean)});if(editor.editable('Labels'))for(const l of editor.project.labels)if(l.objectId===o.id){l.text=o.name;l.position.x+=x-old.x;l.position.y+=y-old.y;}editor.draw();refresh(editor);toast('История места сохранена');return true;};
 $('apply-label').onclick=()=>{const l=editor.selected();if(!l?.kind||!editor.editable('Labels')){toast('Слой подписей заблокирован');return;}const size=Number($('label-size').value),rotation=Number($('label-rotation').value);if(!Number.isFinite(size)||size<6||size>100||!Number.isFinite(rotation)||Math.abs(rotation)>180){toast('Размер: 6–100; поворот: −180…180');return;}editor.snapshot();Object.assign(l,{text:$('label-text').value.trim()||'Без названия',size,rotation,color:$('label-color').value,manual:true,hidden:false});editor.draw();refresh(editor);};
 $('delete-object').onclick=() =>editor.deleteSelected();$('delete-label').onclick=()=>editor.deleteSelected();
 $('apply-style').onclick=()=>{editor.snapshot();const p=editor.project;p.title=$('map-title').value.trim()||'Безымянный мир';p.subtitle=$('map-subtitle').value;p.styling.theme=$('theme').value;p.styling.labels=$('show-labels').checked;p.styling.frame=$('show-frame').checked;for(const k of ['relief','texture','atmosphere'])p.styling[k]=Number($('style-'+k).value);editor.draw();refresh(editor);toast('Оформление атласа обновлено');};$('layout-labels').onclick=()=>{if(!editor.editable('Labels')){toast('Слой подписей скрыт или заблокирован');return;}editor.snapshot();W.labels.layout(editor.project);editor.draw();refresh(editor);};
 $('save').onclick=()=>{if(!editor.project)return;W.storage.save(editor.project);editor.dirty=false;refresh(editor);toast('Проект подготовлен для сохранения');};$('load').onclick=()=>$('file').click();$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const p=await W.storage.load(f);if(editor.project)editor.snapshot();editor.setProject(p);W.libraryUI?.refresh();editor.dirty=false;syncProject();refresh(editor);toast('Атлас возвращён в мастерскую');}catch(err){toast(err.message);}e.target.value='';};
 $('export').onclick=()=>{const p=editor.project;if(!p)return;$('export-size').textContent=`Иллюстрация ${p.width} × ${p.height} px. Без интерфейса и выделений.`;$('export-labels').checked=p.styling.labels;$('export-frame').checked=p.styling.frame;$('export-layers').replaceChildren();for(const l of p.layerOrder){const label=document.createElement('label');label.className='check';const input=document.createElement('input');input.type='checkbox';input.checked=p.layers[l].export;input.onchange=()=>{editor.snapshot();p.layers[l].export=input.checked;refresh(editor);};label.append(input,document.createTextNode(l));$('export-layers').append(label);}$('export-dialog').showModal();};
 $('png').onclick=async()=>{const b=$('png');b.disabled=true;try{await W.storage.png(editor.project,{labels:$('export-labels').checked,frame:$('export-frame').checked});$('export-dialog').close();toast('Иллюстрация PNG готова');}catch(err){toast(err.message);}finally{b.disabled=false;}};$('json').onclick=()=>{W.storage.save(editor.project,true);$('export-dialog').close();toast('Игровой JSON готов');};
 window.addEventListener('beforeunload',e=>{if(editor.dirty){e.preventDefault();e.returnValue='';}});
 syncParams();generate(true).then(()=>{library();buildThumbnails();});
})(WS);
