(function(W){
 const S=W.semantic,states=new WeakMap(),P=S.cfg.detailPatch;
 function ground(p,x,y){const a=W.surface.heightField(p),gx=W.model.clamp(x/5-.5,0,p.cols-1),gy=W.model.clamp(y/5-.5,0,p.rows-1),ix=Math.floor(gx),iy=Math.floor(gy),jx=Math.min(ix+1,p.cols-1),jy=Math.min(iy+1,p.rows-1),u=gx-ix,v=gy-iy;return(a[iy*p.cols+ix]*(1-u)+a[iy*p.cols+jx]*u)*(1-v)+(a[jy*p.cols+ix]*(1-u)+a[jy*p.cols+jx]*u)*v;}
 function state(p){let s=states.get(p);if(!s){s={patches:new Map(),paths:null};states.set(p,s);}return s;}
 // Match the renderer's quadratic road curve. Index it once, independent of chunks.
 function paths(p){const s=state(p);if(s.paths)return s.paths;const grid=new W.scene.Grid(),points=[];
  for(const [layer,items]of [['road',p.roads],['river',p.rivers]])for(const [ri,r]of items.entries()){
   const route=W.atlas?.curve(r)||r.points;let prev=route[0];if(!prev)continue;const samples=[prev];
   for(let i=1;i<route.length;i++){const control=route[i],end=i===route.length-1?control:{x:(control.x+route[i+1].x)/2,y:(control.y+route[i+1].y)/2},begin=prev,n=Math.max(1,Math.ceil((Math.hypot(control.x-begin.x,control.y-begin.y)+Math.hypot(end.x-control.x,end.y-control.y))/2));for(let j=1;j<=n;j++){const t=j/n,q=1-t;samples.push({x:q*q*begin.x+2*q*t*control.x+t*t*end.x,y:q*q*begin.y+2*q*t*control.y+t*t*end.y});}prev=end;}
   let distance=0,next=0;for(let i=1;i<samples.length;i++){const a=samples[i-1],b=samples[i],length=Math.hypot(b.x-a.x,b.y-a.y);if(!length)continue;const angle=Math.atan2(b.y-a.y,b.x-a.x),width=r.width;grid.add({a,b,width,layer,angle},{x:Math.min(a.x,b.x)-width-4,y:Math.min(a.y,b.y)-width-4,width:Math.abs(a.x-b.x)+2*width+8,height:Math.abs(a.y-b.y)+2*width+8});while(next<=distance+length){const t=(next-distance)/length;points.push({id:S.id(p,layer,r.id||ri,Math.round(next)),x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,angle,width,layer,step:Math.round(next)});next+=3;}distance+=length;}
  }s.paths={grid,points};return s.paths;
 }
 function proximity(p,x,y){let road=Infinity,river=Infinity,angle=0;for(const s of paths(p).grid.query({x:x-8,y:y-8,width:16,height:16})){const dx=s.b.x-s.a.x,dy=s.b.y-s.a.y,t=W.model.clamp(((x-s.a.x)*dx+(y-s.a.y)*dy)/(dx*dx+dy*dy)),d=Math.hypot(x-s.a.x-t*dx,y-s.a.y-t*dy)-s.width*.5;if(s.layer==='river')river=Math.min(river,d);else if(d<road){road=d;angle=s.angle;}}return{road,river,angle};}
 function safe(p,x,y,size=1,roads=true){if(x<size||y<size||x>p.width-size||y>p.height-size)return false;for(const [dx,dy]of [[0,0],[-size,-size],[size,-size],[-size,size],[size,size]])if(ground(p,x+dx,y+dy)<p.seaLevel+.002)return false;const d=proximity(p,x,y);return d.river>size+1&&(!roads||d.road>size+1);}
 function patch(p,bx,by){const s=state(p),key=bx+','+by;if(s.patches.has(key)){const a=s.patches.get(key);s.patches.delete(key);s.patches.set(key,a);return a;}const list=[];
  for(let gy=Math.ceil(by*P/4);gy*4<(by+1)*P;gy++)for(let gx=Math.ceil(bx*P/4);gx*4<(bx+1)*P;gx++){
   if(S.random(p,'material-patch-density',Math.floor(gx/5),Math.floor(gy/5))<.25||S.random(p,'material-density',gx,gy)>.7)continue;const r=S.random(p,'material',gx,gy),x=gx*4+S.random(p,'material-x',gx,gy)*3,y=gy*4+S.random(p,'material-y',gx,gy)*3;if(x<0||y<0||x>=p.width||y>=p.height)continue;
   const i=W.model.index(p,x,y),biome=p.biomes[i],e=ground(p,x,y),water=e<p.seaLevel,shore=W.coast.distance(p)[i],kind=water?(shore<12?'foam':'wave'):shore<10&&e-p.seaLevel<.02?(p.humidity[i]>.7?'reed':'pebble'):({mountain:'scree',rocky:'scree',snow:r>.6?'snowbreak':'scree',swamp:r>.55?'puddle':'reed',forest:'leaf',conifer:'log',deadforest:'root',cursed:'root',waste:'crack',ruined:'rubble',tundra:'stone',plain:r>.7?'drygrass':'grass',valley:'grass',coast:'pebble'})[biome]||'grass';
   list.push({id:S.id(p,'material',gx,gy),x,y,kind,angle:S.random(p,'angle',gx,gy)*Math.PI*2,size:.25+r*.85,tier:r>.48?'inspection':'material',bounds:{x:x-3,y:y-3,width:6,height:6}});
  }s.patches.set(key,list);while(s.patches.size>S.cfg.maxDetailPatches)s.patches.delete(s.patches.keys().next().value);return list;
 }
 function materials(p,r,z){const weights=S.weights(z);if(!weights.material)return[];const out=[];for(let y=Math.max(0,Math.floor((r.y-3)/P));y<=Math.floor(Math.min(p.height,r.y+r.height+3)/P);y++)for(let x=Math.max(0,Math.floor((r.x-3)/P));x<=Math.floor(Math.min(p.width,r.x+r.width+3)/P);x++)for(const f of patch(p,x,y))if(weights[f.tier]>0&&W.scene.intersects(f.bounds,r))out.push(f);return out.sort((a,b)=>a.y-b.y||a.x-b.x);}
 function primitive(c,f,alpha=1){c.save();c.globalAlpha*=alpha;c.translate(f.x,f.y);c.rotate(f.angle||0);const s=f.size||1;c.lineWidth=.18;c.lineCap='round';c.strokeStyle='#454c39';c.fillStyle='#b8af86';c.beginPath();
  if(['scree','stone','pebble','rubble'].includes(f.kind)){c.moveTo(-s,0);c.lineTo(-s*.25,-s*.65);c.lineTo(s*.65,-s*.4);c.lineTo(s,s*.35);c.lineTo(-s*.7,s*.5);c.closePath();c.fillStyle=f.kind==='rubble'?'#8e8266':'#777b69';c.fill();c.stroke();c.beginPath();c.moveTo(-s*.25,-s*.65);c.lineTo(s*.65,-s*.4);c.strokeStyle='#c1bda2';c.stroke();}
  else if(['wave','foam','snowbreak'].includes(f.kind)){c.strokeStyle=f.kind==='wave'?'#9dbbb780':f.kind==='foam'?'#d4debfbb':'#727d7188';c.moveTo(-s,0);c.quadraticCurveTo(0,-s*.4,s,0);c.stroke();}
  else if(f.kind==='puddle'){c.fillStyle='#31585399';c.ellipse(0,0,s*1.4,s*.6,0,0,7);c.fill();c.strokeStyle='#a0b6a777';c.stroke();}
  else if(['log','root','crack'].includes(f.kind)){c.strokeStyle=f.kind==='crack'?'#51483399':'#4d4735';c.lineWidth=f.kind==='log'?.6:.22;c.moveTo(-s,0);c.lineTo(0,s*.3);c.lineTo(s,-s*.4);c.moveTo(0,s*.3);c.lineTo(s*.3,s);c.stroke();}
  else if(f.kind==='path'){c.strokeStyle='#b8a57b99';c.lineWidth=s;c.moveTo(-f.length/2,0);c.lineTo(f.length/2,0);c.stroke();}
  else{c.strokeStyle=f.kind==='drygrass'?'#b6a27499':f.kind==='reed'?'#b1ae70':'#9aab6e99';for(let k=-1;k<=1;k++){c.moveTo(0,s*.4);c.quadraticCurveTo(k*s*.2,-s*.3,k*s*.6,-s);}c.stroke();}
  c.restore();
 }
 function drawMaterials(c,p,on,r,options){const z=options.semanticZoom??1,w=S.weights(z);let count=0;for(const f of materials(p,r,z)){const water=f.kind==='wave'||f.kind==='foam';if(water!==(options.materialLayer==='water')||(water?!on('Water'):!on('Terrain')))continue;primitive(c,f,w[f.tier]*.75);count++;}return count;}
 function tree(c,f){const s=f.size;c.save();c.translate(f.x,f.y);c.globalAlpha*=f.alpha??1;c.lineCap='round';c.fillStyle='#263a2b44';c.beginPath();c.ellipse(s*.1,s*.08,s*.36,s*.12,0,0,7);c.fill();c.strokeStyle='#584e38';c.lineWidth=.45;c.beginPath();c.moveTo(0,0);c.lineTo(0,-s*.72);c.stroke();
  if(f.kind==='deadTree'){c.lineWidth=.28;for(let k=0;k<5;k++){const y=-s*(.2+k*.11),dir=k%2?1:-1;c.beginPath();c.moveTo(0,y);c.lineTo(s*.22*dir,y-s*.13);c.lineTo(s*.28*dir,y-s*.28);c.stroke();}}
  else if(f.kind==='pine'){for(let k=0;k<3;k++){const y=-s*(.3+k*.21),b=s*(.36-k*.075);c.fillStyle=['#344c39','#405b42','#5e7150'][k];c.beginPath();c.moveTo(-b,y+s*.13);c.lineTo(0,y-s*.32);c.lineTo(b,y+s*.13);c.closePath();c.fill();c.strokeStyle='#263b2d99';c.lineWidth=.15;c.stroke();}}
  else{for(let k=0;k<5;k++){const angle=k*2.4;c.fillStyle=['#485b35','#596a3d','#71804a','#405735','#879159'][k];c.beginPath();c.ellipse(Math.cos(angle)*s*.14,-s*.48+Math.sin(angle)*s*.15,s*.23,s*.21,0,0,7);c.fill();}}
  c.restore();
 }
 function hierarchy(p,parent,z){const w=S.weights(z),mountain=parent.layer==='Mountains',out=[];if(!w.hierarchy)return out;const size=parent.size,cols=Math.max(2,Math.ceil(size/(mountain?14:8))),seed=parent.uid||parent.id;
  for(let j=0;j<cols;j++)for(let i=0;i<cols;i++){const r=S.hash(seed,i,j),xx=(i+.2+S.hash(seed,i,j,'x')*.6)/cols-.5,yy=(j+.2+S.hash(seed,i,j,'y')*.6)/cols-.8;if((xx*xx/.25+(yy+.3)**2/.25)>1||r<.18)continue;const x=parent.x+xx*size*.85,y=parent.y+yy*size*.8,index=W.model.index(p,x,y),biome=p.biomes[index];if(mountain?!parent.explicit&&!['mountain','snow','rocky'].includes(biome):!safe(p,x,y,1,false)||!parent.explicit&&p.forestDensity[index]<r*.7)continue;if(!mountain&&!parent.explicit&&(W.config.biomes[biome]?.layer!=='Vegetation'||proximity(p,x,y).road<2||W.scene.objects(p,{x:x-30,y:y-30,width:60,height:60}).some(o=>o.layer!=='Decorations'&&Math.hypot(o.position.x-x,o.position.y-y)<30)))continue;if(!mountain&&proximity(p,x,y).river<2)continue;
   const childSize=mountain?7+r*5:4+r*4;out.push({uid:seed+':child:'+i+':'+j,x,y,size:childSize,variant:r,layer:parent.layer,id:parent.rock?88:mountain?(biome==='snow'?20:16)+Math.floor(r*4):['deadforest','cursed'].includes(biome)||parent.dead?93:biome==='conifer'?28+Math.floor(r*4):92,kind:mountain?'peak':['deadforest','cursed'].includes(biome)?'deadTree':biome==='conifer'?'pine':'tree',alpha:w.hierarchy,bounds:{x:x-childSize*.5,y:y-childSize,width:childSize,height:childSize*1.2}});
  }return out.sort((a,b)=>a.y-b.y||a.x-b.x);
 }
 function drawPaths(c,p,r,z,layer){const w=S.weights(z);if(!w.material)return 0;let count=0;for(const f of paths(p).points){if(f.layer!==layer||f.x<r.x-8||f.y<r.y-8||f.x>r.x+r.width+8||f.y>r.y+r.height+8)continue;const v=S.hash(f.id),nx=-Math.sin(f.angle),ny=Math.cos(f.angle),side=v>.5?1:-1,off=(f.width*.5+.5)*side;primitive(c,{x:f.x+nx*off,y:f.y+ny*off,size:.25+v*.45,kind:layer==='road'?'pebble':v>.6?'reed':'foam',angle:f.angle},w.material*.75);if(w.inspection){primitive(c,{x:f.x+nx*f.width*.23,y:f.y+ny*f.width*.23,size:.15,length:2.2,kind:'path',angle:f.angle},w.inspection*.65);}count++;}return count;}
 function invalidate(p,r,objects=false){if(!r){states.delete(p);return;}const s=states.get(p);if(!s)return;for(const k of s.patches.keys()){const [x,y]=k.split(',').map(Number);if(W.scene.intersects(S.expand({x:x*P,y:y*P,width:P,height:P},S.cfg.editPadding),r))s.patches.delete(k);}}
 function features(p,r,z){const list=materials(p,r,z).map(f=>({id:f.id,x:f.x,y:f.y,kind:f.kind}));for(const layer of ['Mountains','Vegetation'])for(const parent of W.scene.sprites(p,r,layer))for(const f of hierarchy(p,parent,z))if(W.scene.intersects(f.bounds,r))list.push({id:f.uid,x:f.x,y:f.y,kind:f.kind});for(const o of W.scene.objects(p,r))for(const f of W.settlement?.children(p,o,z)||[])if(W.scene.intersects(f.bounds,r))list.push({id:f.uid,x:f.x,y:f.y,kind:f.kind});return list.sort((a,b)=>a.id.localeCompare(b.id));}
 W.detail={ground,proximity,safe,materials,primitive,drawMaterials,drawPaths,hierarchy,tree,paths,invalidate,features,stats:p=>({patches:state(p).patches.size,limit:S.cfg.maxDetailPatches})};
})(WS);
