(function(W){
 const states=new WeakMap(),S=128;
 const intersects=(a,b)=>a.x+a.width>=b.x&&a.y+a.height>=b.y&&a.x<=b.x+b.width&&a.y<=b.y+b.height;
 const bounds=W.objects.bounds;
 class Grid{
  constructor(){this.cells=new Map();this.count=0;}
  add(o,b){o.bounds=b;this.count++;for(let y=Math.floor(b.y/S);y<=Math.floor((b.y+b.height)/S);y++)for(let x=Math.floor(b.x/S);x<=Math.floor((b.x+b.width)/S);x++){const k=x+','+y;if(!this.cells.has(k))this.cells.set(k,[]);this.cells.get(k).push(o);}}
  query(r,layer){const out=[],seen=new Set();for(let y=Math.floor(r.y/S);y<=Math.floor((r.y+r.height)/S);y++)for(let x=Math.floor(r.x/S);x<=Math.floor((r.x+r.width)/S);x++)for(const o of this.cells.get(x+','+y)||[]){if(seen.has(o)||layer&&o.layer!==layer)continue;seen.add(o);if(intersects(o.bounds,r))out.push(o);}return out;}
 }
 function state(p){let s=states.get(p);if(s)return s;s={blocks:new Map(),objects:new Grid(),riverCells:new Set(),noise:W.random.noise(p.seed+'detail')};for(const o of p.objects)s.objects.add({...o},bounds(o));for(const r of p.rivers)for(const pt of r.points)s.riverCells.add(W.model.index(p,pt.x,pt.y));states.set(p,s);return s;}
 function block(p,s,bx,by){const key=bx+','+by;if(s.blocks.has(key))return s.blocks.get(key);const list=[],n=s.noise,rx=bx*S,ry=by*S;
  // Global lattices are only partitioned for lookup, never seeded per chunk.
  for(const layer of ['Mountains','Vegetation']){const mountain=layer==='Mountains',dx=mountain?37:15,dy=mountain?34:14,ox=mountain?35:20,oy=mountain?40:20;for(let gy=Math.ceil((ry-oy)/dy);oy+gy*dy<ry+S;gy++)for(let gx=Math.ceil((rx-ox)/dx);ox+gx*dx<rx+S;gx++){const x=ox+gx*dx,y=oy+gy*dy;if(x<ox||y<oy||x>=p.width-15||y>=p.height-15)continue;const r=W.semantic.random(p,'atlas-scatter',gx,gy,layer),xx=x+(mountain?n(x/8,y/8)-.5:r-.5)*(mountain?28:17),yy=y+(n(x/(mountain?8:6)+(mountain?7:0),y/(mountain?8:6))-.5)*(mountain?25:17),i=W.model.index(p,xx,yy),b=p.biomes[i],def=W.config.biomes[b];let id,size,variant;
   if(mountain){if(!['mountain','snow','rocky'].includes(b)){if(p.terrain[i]<p.seaLevel+.025||b==='swamp'||r>.20||n(xx/85+80,yy/85)<.54)continue;id=88;size=7+r*24;variant=r;}else{if(b==='rocky'&&r<.70)continue;variant=W.semantic.random(p,'mountain-shape',gx,gy);const chain=r>.88&&b!=='rocky';size=b==='rocky'?21+r*23:chain?76+r*10:40+r*34;id=b==='rocky'?2:chain?def.sprite:16+(b==='snow'?4:0)+Math.min(3,Math.floor(variant*4));}}
   else{if(p.terrain[i]<p.seaLevel||!(def?.layer==='Vegetation'||['plain','valley','coast','ruined'].includes(b))||r>p.forestDensity[i]*.96||s.riverCells.has(i)||n(xx/62+140,yy/62)>.73)continue;const proximity=W.detail?.proximity(p,xx,yy);if(proximity&&(proximity.river<3||proximity.road<5))continue;if(s.objects.query({x:xx-30,y:yy-30,width:60,height:60}).some(o=>o.layer!=='Decorations'&&Math.hypot(o.position.x-xx,o.position.y-yy)<30))continue;variant=W.semantic.random(p,'forest-shape',gx,gy);const evergreen=b==='conifer'||b!=='forest'&&p.temperature[i]<.36,autumn=n(xx/180+51,yy/180)>.76;id=['deadforest','cursed'].includes(b)?(variant>.45?93:6):b==='swamp'?7:evergreen?28+Math.min(3,Math.floor(variant*4)):autumn?25:[24,26,27][Math.min(2,Math.floor(variant*3))];size=['deadforest','cursed'].includes(b)?18+r*20:b==='swamp'?23+r*13:28+r*22;if(b==='forest'&&variant>.96){id=92;size=40+r*8;}}
   list.push({uid:W.semantic?.id(p,layer,gx,gy)||layer+gx+","+gy,x:xx,y:yy,id,size,variant,layer,bounds:{x:xx-size*.5-2,y:yy-size*.8-2,width:size+4,height:size+4}});
  }}s.blocks.set(key,list);return list;
 }
 function sprites(p,r,layer){const s=state(p),out=[],pad=150;for(let y=Math.max(0,Math.floor((r.y-pad)/S));y<=Math.floor(Math.min(p.height,r.y+r.height+pad)/S);y++)for(let x=Math.max(0,Math.floor((r.x-pad)/S));x<=Math.floor(Math.min(p.width,r.x+r.width+pad)/S);x++)for(const o of block(p,s,x,y))if(o.layer===layer&&intersects(o.bounds,r))out.push(o);out.sort((a,b)=>a.y-b.y||a.x-b.x||a.uid.localeCompare(b.uid));return out;}
 W.scene={replaceObjects(p){const s=state(p);s.objects=new Grid();for(const o of p.objects)s.objects.add({...o},bounds(o));},Grid,bounds,intersects,sprites,objects:(p,r,l)=>state(p).objects.query(r,l).sort((a,b)=>a.position.y-b.position.y||a.position.x-b.position.x||a.id.localeCompare(b.id)),invalidate(p,r){if(!r){states.delete(p);return;}const s=states.get(p);if(!s)return;for(const k of s.blocks.keys()){const [x,y]=k.split(',').map(Number);if(intersects({x:x*S-180,y:y*S-180,width:S+360,height:S+360},r))s.blocks.delete(k);}},stats(p){const s=state(p);return{objectCount:s.objects.count,blocks:s.blocks.size,entities:[...s.blocks.values()].reduce((n,b)=>n+b.length,0)+s.objects.count};}};
})(WS);
